### ISSUE TITLE
请求新增Google play/map应用拦截规则

### ISSUE THREAD

**Issue by KIL011** [TG-Twilight/AWAvenue-Adblock-Rule#18]
开发者您好，

请问是否可以增加google商店与地图的拦截规则？如截图
![Screenshot_2023-09-07-06-51-49-13_3d9111e2d3171bf4882369f490c087b4](https://github.com/TG-Twilight/AWAvenue-Adblock-Rule/assets/67146465/02f9d164-ad43-42ab-923c-ee9bc5319e81)
![Screenshot_2023-09-07-06-51-39-14_b5a5c5cb02ca09c784c5d88160e2ec24](https://github.com/TG-Twilight/AWAvenue-Adblock-Rule/assets/67146465/0f0a18b2-5d84-41ab-af8b-6ba793166de3)

**Comment by TG-Twilight** [comment]
这种广告不是单独的广告sdk喔，只能靠修改软件/hook去掉，如果你能抓到单独的广告链接可以提交给我。

Jiawei ***@***.***> 于 2023年9月7日周四 12:04写道：
