### ISSUE TITLE
快手

### ISSUE THREAD

**Issue by Dusk0531** [TG-Twilight/AWAvenue-Adblock-Rule#21]
[static.yximgs.com为快手图标]
v*-ad.video.yximgs.com为广告域名
![Uploading Screenshot_2023-11-07-21-00-27-03_73230ea9d8560975a5358fd7bd043f47.jpg…]()

**Comment by TG-Twilight** [comment]
已修复，感谢反馈！同时“v*-ad.video.yximgs.com”之前就添加了
